export const LIGHT = {
  COLORS: {
    MODAL_BACKGROUND: '#FFFFFF',
    STATUSBAR_BACKGROUND: '#002147',
    BACKGROUND: '#FFFFFF',
    TOAST_BACKGROUND: '#FFFFFF',
    PANEL_BACKGROUND: '#F6F6F6',
    TEXT_INPUT_BACKGROUND: '#FFFFFF',
    TEXT_INPUT_NOT_EDITABLE_BACKGROUND: '#EEEEEE',
    BUTTON_BACKGROUND: '#0085FF',
    BUTTON_LOADING_BACKGROUND: '#707273',

    TEXT_PRIMARY: '#000000',
    TEXT_SECONDARY: '#666666',
    TEXT_PLACEHOLDER: '#798593',
    TEXT_BUTTON: '#FFFFFF',
  },
}
